### ISSUE TITLE
Building new translators issue: "ReferenceError: filename is not defined"

### ISSUE THREAD

**Issue by Looxloox** [zotero/translation-server#114]
Following the [tutorial proposed by Wikimedia](https://www.mediawiki.org/wiki/Citoid/Creating_Zotero_translators) to build new translators, i constructed a "Wikimedia.js" file exactly the way it is described (you can see the file [there](https://github.com/MGWiki-med/translators/blob/master/Mediawiki.js) ).
Unfortunately, i can't possibly restart the server after adding this new file to the translators directory (using Docker as well as npm).
The error is:
`> node src/server.js

(node:23034) UnhandledPromiseRejectionWarning: ReferenceError: filename is not defined
    at Object.load (/home/abrul/Prog/translation-server/src/translators.js:129:77)
    at async Object.init (/home/abrul/Prog/translation-server/src/translators.js:48:18)
(node:23034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23034) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
Any idea ?

**Comment by dstillman** [comment]
We'll fix that ReferenceError but the message it's trying to display is "Invalid or missing translator metadata JSON object", which happens when the metadata at the top of the file [can't be parsed](https://github.com/zotero/translation-server/blob/8dd12156def9cbbae7e2df4ec35392c1f63f5125/src/translators.js#L129) as JSON.

**Comment by Looxloox** [comment]
Ok, i finally found syntax errors in the URL declaration ("\\." instead of "\\\\.")
Thank you for your help

**Comment by dstillman** [comment]
Leaving this open to fix the error message
