### ISSUE TITLE
ReferenceError: requestText is not defined

### ISSUE THREAD

**Issue by stefan-sigle** [zotero/translation-server#163]
Running Zotero translate server latest via docker-compose. Worked out perfectly until yesterday, but now does not resolve any DOI identifiers anymore. PMIDs are working fine still.

Request is a `POST` on `http://localhost:1969/search` with a DOI like `10.1200/JCO.2023.41.17_suppl.LBA3000`

Logs are the following:

```
(3)(+0000001): Translate: All translator detect calls and RPC calls complete:

(3)(+0000000): 	DOI Content Negotiation: 100

(3)(+0000000): 	mEDRA: 105

(5)(+0000000): Translate: Running handler 0 for translators

(4)(+0000001): Translate: Parsing code for DOI Content Negotiation (b28d0d42-8549-4c6d-83fc-8382874a5cb9, 2023-09-22 09:54:11)

(3)(+0000000): Translate: Beginning translation with DOI Content Negotiation

(node:62) UnhandledPromiseRejectionWarning: ReferenceError: requestText is not defined
    at processDOI (eval at <anonymous> (/app/src/translation/sandboxManager.js:70:4), <anonymous>:67:17)
    at doSearch (eval at <anonymous> (/app/src/translation/sandboxManager.js:70:4), <anonymous>:62:9)
    at Zotero.Translate.Search.rest (/app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1406:49)
    at loadPromise.then (/app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1396:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:62) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

Are we rate limited for DOI lookups or anything? Does anybody else have trouble?

**Comment by stefan-sigle** [comment]
Update: so i build the docker image locally and it works like a charm.

**Comment by dstillman** [comment]
Sorry, we haven't pushed an updated version to Docker Hub in a few years. We'll try to get to that soon. In the meantime, latest code in git should work fine.
