### ISSUE TITLE
Don't fail on 502 from search translator

### ISSUE THREAD

**Issue by dstillman** [zotero/translation-server#178]
https://forums.zotero.org/discussion/119968/all-isbns-return-the-error-an-error-occured-while-citing-this-source

9782294703041 on ZoteroBib is failing intermittently due to a 502 from LoC:

```
Error: HTTP request to https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1 rejected with status 502
```

This seems to cause translation-server to return 502, which causes CloudFront to return 502, which causes a CORS error in the browser since it's missing our CORS headers (but the response is just "{"message": "Internal server error"}", which is meaningless to us anyway).

When it works it's from BnF ISBN.

We should make sure that translation-server moves on to the next translator if it encounters an unexpected HTTP error.

**Comment by adomasven** [comment]
translation-server doesn't return 502. It returns 500, but I guess that's CF converting it to 502. Anyway, Search Translate logs a line and automatically falls back to the next translator when no items are found:
https://github.com/zotero/translate/blob/fa4c0524f35cfda4a675a78f51c0eafb40d4ab33/src/translation/translate.js#L2778-L2792

I think we're just unable to resolve that ISBN without LoC?

**Comment by dstillman** [comment]
No, see above — when it works it's from BnF. The 502 from LoC seems to be causing it to fail before BnF can finish.

Here's the failure:

```

2024-11-29T10:13:23.921Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000001): HTTP GET https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1
--
2024-11-29T10:13:23.970Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000049): Translate: Could not find a result using Library of Congress ISBN -- trying next translator
2024-11-29T10:13:23.983Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000013): HTTP GET https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1 failed with status code 502
2024-11-29T10:13:23.983Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(4)(+0000000): Translate: Parsing code for BnF ISBN (f349954c-9957-4b5f-be24-1a8bb52f7fbd, 2021-07-30 21:23:00)
2024-11-29T10:13:23.983Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000000): Translate: Beginning translation with BnF ISBN
2024-11-29T10:13:23.984Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000001): Translate: resolving URL https://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn%20all%20%229782294703041%22
2024-11-29T10:13:23.984Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000000): Translate: resolved to https://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn%20all%20%229782294703041%22
2024-11-29T10:13:23.984Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000000): Zotero.HTTP.doGet is deprecated. Use Zotero.HTTP.request
2024-11-29T10:13:23.984Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	INFO	(3)(+0000000): HTTP GET https://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn%20all%20%229782294703041%22
2024-11-29T10:13:23.985Z	0a54dba2-a5ec-46b0-a509-e5e570ccc7c0	ERROR	Unhandled Promise Rejection 	{     "errorType": "Runtime.UnhandledPromiseRejection",     "errorMessage": "Error: HTTP request to https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1 rejected with status 502",     "reason": {         "errorType": "Error",         "errorMessage": "HTTP request to https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1 rejected with status 502",         "message": "HTTP request to https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1 rejected with status 502",         "status": 502     },     "promise": {},     "stack": [         "Runtime.UnhandledPromiseRejection: Error: HTTP request to https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1 rejected with status 502",         "    at process.<anonymous> (/var/runtime/index.js:35:15)",         "    at process.emit (events.js:400:28)",         "    at process.emit (domain.js:475:12)",         "    at processPromiseRejections (internal/process/promises.js:245:33)",         "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"     ] }
```

And a success:

```
2024-11-29T10:18:10.408Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): HTTP GET https://lx2.loc.gov/sru/lcdb?operation=searchRetrieve&version=1.1&query=bath.ISBN=^9782294703041&maximumRecords=1
2024-11-29T10:18:10.448Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000040): Translate: Creating translate instance of type import in sandbox
2024-11-29T10:18:10.448Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000000): Translate: Binding sandbox to http://www.example.com/
2024-11-29T10:18:10.448Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000000): Translate: Parsing code for MARCXML (edd87d07-9194-42f8-b2ad-997c4c7deefd, 2023-04-19 14:30:00)
2024-11-29T10:18:10.449Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000001): Translate: Beginning translation with MARCXML
2024-11-29T10:18:10.449Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): Translate: Creating translate instance of type import in sandbox
2024-11-29T10:18:10.449Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000000): Translate: Binding sandbox to http://www.example.com/
2024-11-29T10:18:10.450Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000001): Translate: Parsing code for MARC (a6ee60df-1ddc-4aae-bb25-45e0537be973, 2024-03-15 21:14:09)
2024-11-29T10:18:10.453Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000003): Translate: Translation successful
2024-11-29T10:18:10.453Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(5)(+0000000): Translate: Running handler 0 for done
2024-11-29T10:18:10.453Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(5)(+0000000): Translate: Running handler 1 for done
2024-11-29T10:18:10.453Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): Translate: Could not find a result using Library of Congress ISBN -- trying next translator
2024-11-29T10:18:10.453Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000000): Translate: Parsing code for BnF ISBN (f349954c-9957-4b5f-be24-1a8bb52f7fbd, 2021-07-30 21:23:00)
2024-11-29T10:18:10.453Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): Translate: Beginning translation with BnF ISBN
2024-11-29T10:18:10.454Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000001): Translate: resolving URL https://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn%20all%20%229782294703041%22
2024-11-29T10:18:10.454Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): Translate: resolved to https://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn%20all%20%229782294703041%22
2024-11-29T10:18:10.454Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): Zotero.HTTP.doGet is deprecated. Use Zotero.HTTP.request
2024-11-29T10:18:10.454Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000000): HTTP GET https://catalogue.bnf.fr/api/SRU?version=1.2&operation=searchRetrieve&query=bib.isbn%20all%20%229782294703041%22
2024-11-29T10:18:10.856Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000402): Translate: Creating translate instance of type import in sandbox
2024-11-29T10:18:10.856Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000000): Translate: Binding sandbox to http://www.example.com/
2024-11-29T10:18:10.857Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(4)(+0000001): Translate: Parsing code for MARCXML (edd87d07-9194-42f8-b2ad-997c4c7deefd, 2023-04-19 14:30:00)
2024-11-29T10:18:10.870Z	44bee9ed-9e7e-4afc-8dca-8e97eceac7b5	INFO	(3)(+0000013): Translate: Beginning translation with MARCXML
[…]
```
