### ISSUE TITLE
Problem in starting server

### ISSUE THREAD

**Issue by shuklaalok7** [zotero/translation-server#40]
I am getting following message when I run `npm start` command. Please help me with this.

![image](https://user-images.githubusercontent.com/1621571/45927272-7240be00-bf4e-11e8-9193-95ffc54d1daa.png)

Here it is in text format, in case someone needs to copy-paste it somewhere.
``` {bash}
ubuntu@ip-172-31-8-27:~/translation-server$ npm start

> translation-server@0.0.1 start /home/ubuntu/translation-server
> node src/server.js

/home/ubuntu/translation-server/node_modules/koa/lib/application.js:62
  listen(...args) {
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/translation-server/src/server.js:28:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-1052-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! translation-server@0.0.1 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the translation-server@0.0.1 start script 'node src/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the translation-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs translation-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls translation-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/translation-server/npm-debug.log
ubuntu@ip-172-31-8-27:~/translation-server$ 
```

**Comment by dstillman** [comment]
You’re using an outdated version of Node.

**Comment by shuklaalok7** [comment]
Thanks @dstillman. It solved this issue for me.
