### ISSUE TITLE
New tests failing

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server#74]
Some of the tests that were recently added are failing for me locally: 
```
  15 passing (979ms)
  4 failing

  1) /export
       should export COinS:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at Server.EventEmitter.emit (domain.js:441:20)
      at emitCloseNT (net.js:1626:8)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)

  2) /export
       should export note as CSL JSON:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at Server.EventEmitter.emit (domain.js:441:20)
      at emitCloseNT (net.js:1626:8)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)

  3) /search
       should translate a PMID:

      AssertionError: expected 501 to equal 200
      + expected - actual

      -501
      +200
      
      at Context.<anonymous> (test/search_test.js:118:10)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

  4) /search
       should translate a PMID with 'pmid:' prefix:

      AssertionError: expected 501 to equal 200
      + expected - actual

      -501
      +200
      
      at Context.<anonymous> (test/search_test.js:131:10)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by mvolz** [comment]
nvm, failed to do submodule update :)
